project_name: wheat_detection

# 显卡号
cuda_id: 0

compound_coef: 0
num_workers: 4
batch_size: 4
head_only: False
lr: 0.0001
optim: 'adamw'
num_epochs: 30
val_interval: 1
save_interval: 2000
es_min_delta: 0.0
es_patience: 0
num_gpus: 1

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
obj_list: ['wheat spike']

load_weights: '/home/huys/wheat_detection/efficientdet-d0.pth'
log_path: '/home/huys/wheat_detection/result/logs/tensorboard/'
saved_path: '/home/huys/wheat_detection/result/model_test/'
debug: False
