project_name: 'n1 baseline'

device: '1, 2'
num_workers: 8

# [b0, b1, b2, b3, b4, b5, b6, b7, b8] -> [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]
img_size: 512
compound_coef: 0
weights: 'efficientdet-d0.pth'
resume: ''

noise_augment: 0

epoch: 100
batch_size: 32

lr: 0.01
scheduler: 'auto'
optim: 'SGD'
momentum: 0.937
weight_decay: 0.0005
beta: (0.9, 0.999)
ema_decay: 0.99

anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
obj_list: ['wheat spike']

input_dir: '/home/huys/wheat_detection'
save_dir: 'outs/'

# eval_thresholds : '(0.5, 0.55, 0.6, 0.65, 0.7, 0.75)'
eval_thresholds : '(0.5, )'
threshold : 0.4
iou_threshold : 0.6
