project_name: wheat_detection

# 显卡号
cuda_id: 3
# 使用多GPU则指定显卡号无效
num_gpus: 4

compound_coef: 4
num_workers: 4
batch_size: 4
head_only: False
lr: 0.0003
# 可选方案 adamw，adamax，SGD
optim: 'adamw'
num_epochs: 40
val_interval: 1
save_interval: 500
es_min_delta: 0.0
es_patience: 0

# 每个轮次都会计算precision，验证的时候慢一些，额外再吃1G左右显存
train_with_precision: False

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
obj_list: ['wheat spike']

load_weights: '/home/huys/wheat_detection/efficientdet-d4.pth'
log_path: '/home/huys/wheat_detection/result/logs/'
saved_path: '/home/huys/wheat_detection/result/model_d4/'
debug: False

# 启用train_with_precision之后，下面参数才有意义
eval_thresholds : '(0.5, 0.55, 0.6, 0.65, 0.7, 0.75)'
threshold : 0.48
iou_threshold : 0.26